project:
  type: website

website:
  title: "AI Lectures"
  navbar:
    left:
      - href: classification_lecture01.qmd
        text: "Lecture 1"
      - href: classification_lecture02.qmd
        text: "Lecture 2"
